name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
      - name: GitHub Pages Deploy
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: "build/"
        uses: maxheld83/ghpages@v0.2.1
